defaults: &defaults
  LOCUM_SERVER:      phosphorus.locum.ru
  LOCUM_LOGIN:       rleefrost
  LOCUM_USER:        hosting_rleefrost
  LOCUM_PASSWORD:    dkH3kAb61
  LOCUM_APPLICATION: yagnob
development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
